/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.GiangVien;

import controller.QLGVDangKyController;
import controller.QLGiangVienController;
import controller.QLLopHocController;
import controller.QLMonHocController;
import controller.QLPhongHocController;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GVDangKy;
import model.GiangVien;
import model.LopHoc;
import model.MonHoc;
import model.PhongHoc;

/**
 *
 * @author admin
 */
public class GVDangKyForm extends javax.swing.JFrame {

    private int selectedRow;
    private String id;
    DefaultTableModel tblModel = new DefaultTableModel();
    QLGVDangKyController qlgvdkc = new QLGVDangKyController();
    List<GVDangKy> listlhgvdk = new ArrayList<>();
    List<LopHoc> listLH = new ArrayList<>();

    /**
     * Creates new form GV_DKview
     */
    public GVDangKyForm(String id) throws ParseException {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initCombobox();
        this.id = id;
        initTable();
        fillTable();
    }

    /**
     * Creates new form MonHocView
     */
    private void initTable() {
        String[] columns = new String[]{"STT", "Mã Lớp", "Tên Lớp", "Môn Học", "Thứ",
            "Tiết", "Ngày Bắt Đầu", "Sĩ Số", "Phòng"};
        tblModel.setColumnIdentifiers(columns);
        tblGVDangKy.setModel(tblModel);
    }

    private void fillTable() {
        try {
            tblModel.setRowCount(0);
            listLH = new QLLopHocController().getListLH();
            int index = 1;
            for (LopHoc lh : listLH) {
                MonHoc mh = new QLMonHocController().getMH(lh.getMaMH());
                PhongHoc ph = new QLPhongHocController().getPH(lh.getMaPH());
                tblModel.addRow(new Object[]{index++, lh.getMaLH(), lh.getTenLH(), mh.getTenMH(),
                    lh.getThu(), lh.getTiet(), lh.getNgayBatDau(), lh.getSiSo(), ph.getTenPH()});
            }
            tblModel.fireTableDataChanged();
        } catch (ParseException ex) {
            ex.printStackTrace();
        }

    }

    private void initCombobox() throws ParseException {
        List<MonHoc> listMH = new QLMonHocController().getListMH();
        for (MonHoc mh : listMH) {
            cbxMaMH.addItem(mh.getMaMH());
        }
    }

    private void resetData() {
        String empty = "";
        txtMaLH.setText(empty);
        txtMaLH.setBackground(null);
        txtTenLH.setText(empty);
        txtTenLH.setBackground(null);
        txtTiet.setText(empty);
        txtTiet.setBackground(null);
        txtNgayBatDau.setText(empty);
        txtNgayBatDau.setBackground(null);
        txtSiSo.setText(empty);
        txtSiSo.setBackground(null);
        txtSoTC.setText(empty);
        txtSoTC.setBackground(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnTaiLai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGVDangKy = new javax.swing.JTable();
        btnThoat = new javax.swing.JButton();
        cbxMaMH = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        txtSoTC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaLH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbThu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTiet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenLH = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        lbTenMon = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtSiSo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("ĐĂNG KÍ GIẢNG DẠY");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconsearch16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm Môn Học");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnDangKy.setText("Đăng Kí");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        btnTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnTaiLai.setText("Tải Lại");
        btnTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiLaiActionPerformed(evt);
            }
        });

        tblGVDangKy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Tên Lớp", "Tên Môn", "Tên Phòng", "Thứ", "Tiết", "Ngày Bắt Đầu", "Sĩ Số"
            }
        ));
        tblGVDangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGVDangKyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGVDangKy);

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconthoat16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        cbxMaMH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMaMHItemStateChanged(evt);
            }
        });

        jLabel5.setText("Số tín chỉ:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã Lớp: ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tên Lớp:");

        lbThu.setText("...");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tiết Học: ");

        jLabel9.setText("Ngày Bắt Đầu: ");

        jLabel13.setText("Thứ: ");

        jLabel10.setText("Sĩ số");

        jLabel11.setText("Môn Học: ");

        lbTenMon.setText("Tên môn học");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtTenLH, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNgayBatDau)
                                .addComponent(txtTiet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxMaMH, 0, 75, Short.MAX_VALUE)
                                    .addComponent(txtSiSo))
                                .addGap(18, 18, 18)
                                .addComponent(lbTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbThu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(btnTimKiem)
                                .addGap(62, 62, 62)
                                .addComponent(btnDangKy)
                                .addGap(69, 69, 69)
                                .addComponent(btnTaiLai)
                                .addGap(67, 67, 67)
                                .addComponent(btnThoat)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTenLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTenMon)
                            .addComponent(jLabel11)
                            .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSiSo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtSoTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lbThu))))
                .addGap(15, 15, 15)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnDangKy)
                    .addComponent(btnTaiLai)
                    .addComponent(btnThoat))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn thoát hay không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbxMaMHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMaMHItemStateChanged
        String maMH = cbxMaMH.getSelectedItem().toString();
        try {
            MonHoc mh = new QLMonHocController().getMH(maMH);
            lbTenMon.setText(mh.getTenMH());
        } catch (ParseException ex) {
            Logger.getLogger(GVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_cbxMaMHItemStateChanged

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng ký môn này không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        GiangVien gv = new QLGiangVienController().getGVById(this.id);
        String maGV = gv.getMaGV();
        selectedRow = tblGVDangKy.getSelectedRow();
        if (selectedRow >= 0) {
            LopHoc lh = listLH.get(selectedRow);
            String maLH = lh.getMaLH();
            qlgvdkc.dangKyLopHocGV(maGV, maLH);
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maMH = cbxMaMH.getSelectedItem().toString();
        try {
            List<LopHoc> listLH = new QLLopHocController().timKiemByMaMH(maMH);
            List<GVDangKy> listGVDK = new ArrayList<>();

            tblModel.setRowCount(0);
            int index = 1;
            for (LopHoc lh : listLH) {
                MonHoc mh = new QLMonHocController().getMH(lh.getMaMH());
                PhongHoc ph = new QLPhongHocController().getPH(lh.getMaPH());
                tblModel.addRow(new Object[]{index++, lh.getMaLH(), lh.getTenLH(), mh.getTenMH(),
                    lh.getThu(), lh.getTiet(), lh.getNgayBatDau(), lh.getSiSo(), ph.getTenPH()});
            }
            tblModel.fireTableDataChanged();
        } catch (ParseException ex) {
            Logger.getLogger(GVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblGVDangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblGVDangKyMouseClicked
        selectedRow = tblGVDangKy.getSelectedRow();
        if (selectedRow >= 0) {
            LopHoc lh = listLH.get(selectedRow);
            try {
                MonHoc mh = new QLMonHocController().getMH(lh.getMaMH());
                PhongHoc ph = new QLPhongHocController().getPH(lh.getMaPH());
                txtMaLH.setText(lh.getMaLH());
                txtTenLH.setText(lh.getTenLH());
                txtTiet.setText(lh.getTiet());
                txtNgayBatDau.setText(lh.getNgayBatDau());
                cbxMaMH.setSelectedItem(lh.getMaMH());
                txtSiSo.setText(lh.getSiSo() + "");
                txtSoTC.setText("" + mh.getSoTinChi());
                lbThu.setText(lh.getThu());
            } catch (ParseException ex) {
                Logger.getLogger(GVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblGVDangKyMouseClicked

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiLaiActionPerformed
        resetData();
        fillTable();
    }//GEN-LAST:event_btnTaiLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GVDangKyForm("gv001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxMaMH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTenMon;
    private javax.swing.JLabel lbThu;
    private javax.swing.JTable tblGVDangKy;
    private javax.swing.JTextField txtMaLH;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtSiSo;
    private javax.swing.JTextField txtSoTC;
    private javax.swing.JTextField txtTenLH;
    private javax.swing.JTextField txtTiet;
    // End of variables declaration//GEN-END:variables

}
