/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.GiangVien;

import controller.QLGiangVienController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.GiangVien;
import model.QuanTriVien;

/**
 *
 * @author admin
 */
public class GVForm extends javax.swing.JFrame {

    private String id;
    private GiangVien gv;
    private QLGiangVienController qlgvc = new QLGiangVienController();

    /**
     * Creates new form GVForm
     */
    public GVForm(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        this.id = id;
        viewInfor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaGV = new javax.swing.JTextField();
        txtTenGV = new javax.swing.JTextField();
        txtKhoa = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCapNhap = new javax.swing.JButton();
        btnDKGiangDay = new javax.swing.JButton();
        btnQLMonHoc = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        btnResetToDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin GiảngViên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setText("Mã GiảngViên:");

        jLabel2.setText("Tên GiảngViên: ");

        jLabel3.setText("Khoa: ");

        jLabel4.setText("SĐT: ");

        jLabel6.setText("Email: ");

        txtMaGV.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txtTenGV)
                    .addComponent(txtKhoa)
                    .addComponent(txtSoDT)
                    .addComponent(txtEmail))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnCapNhap.setText("Cập Nhật");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnDKGiangDay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnDKGiangDay.setText("Đăng Kí Giảng Dạy");
        btnDKGiangDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKGiangDayActionPerformed(evt);
            }
        });

        btnQLMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/xem16.png"))); // NOI18N
        btnQLMonHoc.setText("Quản Lý Môn Học");
        btnQLMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMonHocActionPerformed(evt);
            }
        });

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icondx16.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnResetToDefault.setText("Reset to Default");
        btnResetToDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetToDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDKGiangDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQLMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(btnCapNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetToDefault)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDangXuat)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnDKGiangDay)
                        .addGap(25, 25, 25)
                        .addComponent(btnQLMonHoc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhap)
                    .addComponent(btnDangXuat)
                    .addComponent(btnResetToDefault))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewInfor() {
        gv = qlgvc.getGVById(id);
        txtMaGV.setText(gv.getMaGV());
        txtTenGV.setText(gv.getTenGV());
        txtKhoa.setText(gv.getKhoa());
        txtSoDT.setText(gv.getSoDT());
        txtEmail.setText(gv.getEmail());
    }

    private void resetData() {
        String empty = "";
        txtMaGV.setText(empty);
        txtTenGV.setText(empty);
        txtKhoa.setText(empty);
        txtSoDT.setText(empty);
        txtEmail.setText(empty);
        txtMaGV.setBackground(null);
        txtTenGV.setBackground(null);
        txtKhoa.setBackground(null);
        txtSoDT.setBackground(null);
        txtEmail.setBackground(null);
    }

    private boolean isHadEmptyField() {
        StringBuffer sb = new StringBuffer();
        if (txtMaGV.getText().isBlank()) {
            sb.append("Mã giảng viên không đc để trống\n");
            txtMaGV.setBackground(Color.CYAN);
        } else {
            txtMaGV.setBackground(null);
        }
        if (txtTenGV.getText().isBlank()) {
            sb.append("Tên giảng viên không đc để trống\n");
            txtTenGV.setBackground(Color.CYAN);
        } else {
            txtTenGV.setBackground(null);
        }
        if (txtKhoa.getText().isBlank()) {
            sb.append("Khoa không đc để trống\n");
            txtKhoa.setBackground(Color.CYAN);
        } else {
            txtKhoa.setBackground(null);
        }
        if (txtSoDT.getText().isBlank() || txtSoDT.getText().trim().length() != 10) {
            sb.append("Số điện thoại không đc để trống và phải điền đủ 10 số\n");
            txtSoDT.setBackground(Color.CYAN);
        } else {
            txtSoDT.setBackground(null);
        }
        if (txtEmail.getText().isBlank()) {
            sb.append("Email không đc để trống\n");
            txtEmail.setBackground(Color.CYAN);
        } else {
            txtEmail.setBackground(null);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    private void btnDKGiangDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKGiangDayActionPerformed
        try {
            new GVDangKyForm(this.id);
        } catch (ParseException ex) {
            Logger.getLogger(GVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDKGiangDayActionPerformed

    private void btnQLMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMonHocActionPerformed
        try {
            new LichGiangDayForm(this.id);
        } catch (ParseException ex) {
            Logger.getLogger(GVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLMonHocActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        // cập nhập thông tin giảng viên
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn cập nhập thông tin hay không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        if (!isHadEmptyField()) {
            String maGV = txtMaGV.getText().trim();
            String tenGV = txtTenGV.getText().trim();
            String khoa = txtKhoa.getText().trim();
            String soDT = txtSoDT.getText().trim();
            String email = txtEmail.getText().trim();
            gv = new GiangVien(maGV, tenGV, khoa, soDT, email, this.id);
            qlgvc.suaGV(gv);
        }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnResetToDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetToDefaultActionPerformed
        // Trả về dữ liệu ban đầu
        resetData();
        viewInfor();
    }//GEN-LAST:event_btnResetToDefaultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new GVForm("gv001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnDKGiangDay;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLMonHoc;
    private javax.swing.JButton btnResetToDefault;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenGV;
    // End of variables declaration//GEN-END:variables
}
