/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.QuanTriVien;

import controller.QLGiangVienController;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GiangVien;
import model.TaiKhoan;

/**
 *
 * @author admin
 */
public class QLGiangVienForm extends javax.swing.JFrame {

    private DefaultTableModel tblModel = new DefaultTableModel();
    private QLGiangVienController qlgvc = new QLGiangVienController();
    private List<GiangVien> listGV = new ArrayList<>();
    private int selectedRow;

    /**
     * Creates new form QLGiangVienForm
     */
    public QLGiangVienForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        initTable();
        fillTable();
    }

    private void initTable() {
        String[] columns = new String[]{"STT", "Mã Giảng Viên", "Tên Giảng Viên", "Khoa", "SDT", "Email"};
        tblModel.setColumnIdentifiers(columns);
        tblQLGiangVien.setModel(tblModel);
    }

    private void fillTable() {
        tblModel.setRowCount(0);
        listGV = qlgvc.getListGV();
        int index = 1;
        for (GiangVien giangvien : listGV) {
            tblModel.addRow(new Object[]{index++, giangvien.getMaGV(), giangvien.getTenGV(), giangvien.getKhoa(), giangvien.getSoDT(), giangvien.getEmail()});
        }
        tblModel.fireTableDataChanged();
    }

    private void resetData() {
        String empty = "";
        txtTenGV.setText(empty);
        txtTenGV.setBackground(null);
        txtMaGV.setText(empty);
        txtMaGV.setBackground(null);
        txtKhoa.setText(empty);
        txtKhoa.setBackground(null);
        txtSoDT.setText(empty);
        txtSoDT.setBackground(null);
        txtEmail.setText(empty);
        txtEmail.setBackground(null);
    }

    private boolean isHadEmptyField() {
        StringBuffer sb = new StringBuffer();
        if (txtMaGV.getText().isBlank()) {
            sb.append("Mã giảng viên không đc để trống\n");
            txtMaGV.setBackground(Color.CYAN);
        } else {
            txtMaGV.setBackground(null);
        }
        if (txtTenGV.getText().isBlank()) {
            sb.append("Tên giảng viên không đc để trống\n");
            txtTenGV.setBackground(Color.CYAN);
        } else {
            txtTenGV.setBackground(null);
        }
        if (txtKhoa.getText().isBlank()) {
            sb.append("Khoa không đc để trống\n");
            txtKhoa.setBackground(Color.CYAN);
        } else {
            txtKhoa.setBackground(null);
        }
        if (txtSoDT.getText().isBlank() || txtSoDT.getText().trim().length() != 10) {
            sb.append("Số điện thoại không đc để trống và phải điền đủ 10 số\n");
            txtSoDT.setBackground(Color.CYAN);
        } else {
            txtSoDT.setBackground(null);
        }
        if (txtEmail.getText().isBlank()) {
            sb.append("Email không đc để trống\n");
            txtEmail.setBackground(Color.CYAN);
        } else {
            txtEmail.setBackground(null);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtTenGV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblQLGiangVien = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtKhoa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnSua = new javax.swing.JButton();
        txtSoDT = new javax.swing.JTextField();
        btnXoa = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTaiLai = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        txtMaGV = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblQLGiangVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Giảng Viên", "Tên Giảng Viên", "Khoa", "Số ĐT", "Email"
            }
        ));
        tblQLGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblQLGiangVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblQLGiangVien);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Khoa: ");

        jLabel5.setText("Số Điện Thoại: ");

        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconadd16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        jLabel6.setText("Email: ");

        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/qli16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icondelete16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconsearch16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("QUẢN LÝ GIẢNG VIÊN");

        btnTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnTaiLai.setText("Tải Lại");
        btnTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiLaiActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Mã Giảng Viên: ");

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconthoat16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel3.setText("Tên Giảng Viên: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTimKiem)
                                .addGap(18, 18, 18)
                                .addComponent(btnTaiLai)
                                .addGap(18, 18, 18)
                                .addComponent(btnThoat)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(209, 209, 209)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaGV)
                                    .addComponent(txtTenGV)
                                    .addComponent(txtKhoa)
                                    .addComponent(txtSoDT)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnTimKiem)
                    .addComponent(btnTaiLai)
                    .addComponent(btnThoat))
                .addGap(19, 19, 19)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiLaiActionPerformed
        // TODO add your handling code here:
        resetData();
        fillTable();
    }//GEN-LAST:event_btnTaiLaiActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn thoát không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (!(txtMaGV.getText().isBlank())) {
            txtMaGV.setBackground(null);
            String maGV = txtMaGV.getText();
            GiangVien gv = qlgvc.timKiemByMaGV(maGV);
            txtMaGV.setText(gv.getMaGV());
            txtTenGV.setText(gv.getTenGV());
            txtKhoa.setText(gv.getKhoa());
            txtSoDT.setText(gv.getSoDT());
            txtEmail.setText(gv.getEmail());
        } else {
            txtMaGV.setBackground(Color.CYAN);
            JOptionPane.showMessageDialog(rootPane, "Hãy nhập Mã giảng viên cần tìm");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblQLGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblQLGiangVienMouseClicked
        selectedRow = tblQLGiangVien.getSelectedRow();
        if (selectedRow >= 0) {
            GiangVien gv = listGV.get(selectedRow);
            txtMaGV.setText(gv.getMaGV());
            txtTenGV.setText(gv.getTenGV());
            txtKhoa.setText(gv.getKhoa());
            txtSoDT.setText(gv.getSoDT());
            txtEmail.setText(gv.getEmail());
        }
    }//GEN-LAST:event_tblQLGiangVienMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn thực hiện chức năng này không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        selectedRow = tblQLGiangVien.getSelectedRow();
        if (selectedRow >= 0) {
            GiangVien gv = listGV.get(selectedRow);
            qlgvc.xoaGV(gv.getId());
        }
        resetData();
        fillTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        TaiKhoan tk = new TaiKhoan();
        if (!isHadEmptyField()) {
            int choice = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc muốn thực hiện hay không?",
                    "Hỏi", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
            String maGV = txtMaGV.getText().trim();
            String tenGV = txtTenGV.getText().trim();
            String khoa = txtKhoa.getText().trim();
            String soDT = txtSoDT.getText().trim();
            String email = txtEmail.getText().trim();

            GiangVien gv = null;
            gv = qlgvc.timKiemByMaGV(maGV);
            if (gv == null) {
                TaoTKGVDialog tkDialog = new TaoTKGVDialog(this, true);
                tk.setId(tkDialog.taiKhoan.getId());
                gv = new GiangVien(maGV, tenGV, khoa, soDT, email, tk.getId());
                qlgvc.themGV(gv);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Thêm thất bại\nMã giảng viên đã tồn tại");
            }
        }
        fillTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (!isHadEmptyField()) {
            int choice = JOptionPane.showConfirmDialog(this,
                    "Bạn có muốn thực hiện chức năng này không?",
                    "Hỏi", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }

            String maGV = txtMaGV.getText().trim();
            String tenGV = txtTenGV.getText().trim();
            String khoa = txtKhoa.getText().trim();
            String soDT = txtSoDT.getText().trim();
            String email = txtEmail.getText().trim();
            String id = qlgvc.getGVByMaGV(maGV).getId();
            GiangVien gv = new GiangVien(maGV, tenGV, khoa, soDT, email, id);
            if (qlgvc.suaGV(gv)) {
                resetData();
            }
        }
        fillTable();
    }//GEN-LAST:event_btnSuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLGiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLGiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLGiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLGiangVienForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLGiangVienForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblQLGiangVien;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtKhoa;
    private javax.swing.JTextField txtMaGV;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenGV;
    // End of variables declaration//GEN-END:variables
}
