package view.QuanTriVien;

import controller.QuanTriVienController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.QuanTriVien;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class QTVForm extends javax.swing.JFrame {

    private String id;
    private QuanTriVien qtv;
    private QuanTriVienController qtvc = new QuanTriVienController();

    /**
     * Creates new form QTVForm
     */
    public QTVForm(String id) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.id = id;
        viewInfor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaQTV = new javax.swing.JTextField();
        txtTenQTV = new javax.swing.JTextField();
        btnResetToDefault = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnQLGiangVien = new javax.swing.JButton();
        btnQLSinhVien = new javax.swing.JButton();
        btnQLMonHoc = new javax.swing.JButton();
        btnQLPhongHoc = new javax.swing.JButton();
        btnQLLopHoc = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Quản Trị Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel1.setText("Mã QTV:");

        jLabel2.setText("Tên QTV:");

        txtMaQTV.setEnabled(false);

        btnResetToDefault.setText("Reset to Default");
        btnResetToDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetToDefaultActionPerformed(evt);
            }
        });

        btnCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaQTV, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(txtTenQTV)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCapNhat)
                            .addComponent(btnResetToDefault))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaQTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenQTV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCapNhat)
                .addGap(18, 18, 18)
                .addComponent(btnResetToDefault)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        btnQLGiangVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconnguoi16.png"))); // NOI18N
        btnQLGiangVien.setText("Quản Lý Giảng Viên");
        btnQLGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLGiangVienActionPerformed(evt);
            }
        });

        btnQLSinhVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconnguoi16.png"))); // NOI18N
        btnQLSinhVien.setText("Quản Lý Sinh Viên");
        btnQLSinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLSinhVienActionPerformed(evt);
            }
        });

        btnQLMonHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnQLMonHoc.setText("Quản Lý Môn Học");
        btnQLMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLMonHocActionPerformed(evt);
            }
        });

        btnQLPhongHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnQLPhongHoc.setText("Quản Lý Phòng Học");
        btnQLPhongHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLPhongHocActionPerformed(evt);
            }
        });

        btnQLLopHoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnQLLopHoc.setText("Quản Lý Lớp Học");
        btnQLLopHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLLopHocActionPerformed(evt);
            }
        });

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icondx16.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDangXuat)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnQLLopHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLPhongHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLGiangVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLSinhVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQLMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDangXuat))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(btnQLGiangVien)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLSinhVien)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLMonHoc)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLPhongHoc)
                        .addGap(18, 18, 18)
                        .addComponent(btnQLLopHoc)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewInfor() {
        qtv = qtvc.getQTV(id);
        txtMaQTV.setText(qtv.getMaQTV());
        txtTenQTV.setText(qtv.getTenQTV());
    }


    private void btnResetToDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetToDefaultActionPerformed
        // TODO add your handling code here:
        viewInfor();
        txtTenQTV.setBackground(null);
    }//GEN-LAST:event_btnResetToDefaultActionPerformed

    private void btnQLGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLGiangVienActionPerformed
        new QLGiangVienForm();
    }//GEN-LAST:event_btnQLGiangVienActionPerformed

    private void btnQLSinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLSinhVienActionPerformed
        new QLSinhVienForm();
    }//GEN-LAST:event_btnQLSinhVienActionPerformed

    private void btnQLLopHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLLopHocActionPerformed
        try {
            new QLLopHocForm();
        } catch (ParseException ex) {
            Logger.getLogger(QTVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLLopHocActionPerformed

    private void btnQLPhongHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLPhongHocActionPerformed
        new QLPhongHocForm();
    }//GEN-LAST:event_btnQLPhongHocActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn cập nhập thông tin hay không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }

        String maQTV = txtMaQTV.getText();
        String tenQTV = txtTenQTV.getText().trim();
        qtv = new QuanTriVien(maQTV, tenQTV, this.id);
        if (maQTV.length() > 0) {
            qtvc.suaQTV(qtv);
        } else {
            JOptionPane.showMessageDialog(this, "Mã quản trị viên không đc để trống\n", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        dispose();
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnQLMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLMonHocActionPerformed
        try {
            new QLMonHocForm();
        } catch (ParseException ex) {
            Logger.getLogger(QTVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnQLMonHocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QTVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QTVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QTVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QTVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new QTVForm("qtv01").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQLGiangVien;
    private javax.swing.JButton btnQLLopHoc;
    private javax.swing.JButton btnQLMonHoc;
    private javax.swing.JButton btnQLPhongHoc;
    private javax.swing.JButton btnQLSinhVien;
    private javax.swing.JButton btnResetToDefault;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtMaQTV;
    private javax.swing.JTextField txtTenQTV;
    // End of variables declaration//GEN-END:variables
}
