/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.SinhVien;

import controller.QLGVDangKyController;
import controller.QLGiangVienController;
import controller.QLLopHocController;
import controller.QLMonHocController;
import controller.QLPhongHocController;
import controller.QLSVDangKyController;
import controller.QLSinhVienController;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.GVDangKy;
import model.GiangVien;
import model.LopHoc;
import model.MonHoc;
import model.PhongHoc;
import model.SinhVien;

/**
 *
 * @author admin
 */
public class SVDangKyForm extends javax.swing.JFrame {
    private int selectedRow;
    private String id;
    DefaultTableModel tblModel = new DefaultTableModel();
    List<GVDangKy> listgvdk = new ArrayList<>();
    QLGVDangKyController qlgvdkc = new QLGVDangKyController();
    QLSVDangKyController qlsvdkc = new QLSVDangKyController();
    QLGiangVienController qlgvc = new QLGiangVienController();
    QLSinhVienController qlsvc = new QLSinhVienController();
    QLLopHocController qllhc = new QLLopHocController();
    QLMonHocController qlmhc = new QLMonHocController();
    QLPhongHocController qlphc = new QLPhongHocController();

    /**
     * Creates new form SV_DKTCView
     */
    public SVDangKyForm(String id) throws ParseException {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initCombobox();
        this.id = id;
        initTable();
        fillTable();
    }

    private void initTable() {
        String[] columns = new String[]{"STT", "Mã Lớp", "Tên Lớp", "Tên Môn", "Thứ",
            "Tiết", "Ngày Bắt Đầu", "Sĩ Số", "Giảng Viên", "Phòng"};
        tblModel.setColumnIdentifiers(columns);
        tblDKTinChi.setModel(tblModel);
    }

    private void fillTable() {
        tblModel.setRowCount(0);
        listgvdk = qlgvdkc.getListLopHocTatCaGVDangKy();
        int index = 1;
        for (GVDangKy gvdk : listgvdk) {
            GiangVien gv = qlgvc.getGVByMaGV(gvdk.getMaGV());
            try {
                LopHoc lh = qllhc.getLH(gvdk.getMaLH());
                MonHoc mh = qlmhc.getMH(lh.getMaMH());
                PhongHoc ph = qlphc.getPH(lh.getMaPH());
                tblModel.addRow(new Object[]{index++, lh.getMaLH(), lh.getTenLH(), mh.getTenMH(), lh.getThu(),
                    lh.getTiet(), lh.getNgayBatDau(), lh.getSiSo(), gv.getTenGV(), ph.getTenPH()});
                
            } catch (ParseException ex) {
                Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        tblModel.fireTableDataChanged();
    }

    private void resetData() {
        String empty = "";
        txtMaLH.setText(empty);
        txtMaLH.setBackground(null);
        txtTenLH.setText(empty);
        txtTenLH.setBackground(null);
        txtTiet.setText(empty);
        txtTiet.setBackground(null);
        txtNgayBatDau.setText(empty);
        txtNgayBatDau.setBackground(null);
        txtTenGV.setText(empty);
        txtTenGV.setBackground(null);
        txtSoTC.setText(empty);
        txtSoTC.setBackground(null);
    }

    private void initCombobox() throws ParseException {
        List<MonHoc> listMH = new QLMonHocController().getListMH();
        for (MonHoc mh : listMH) {
            cbxMaMH.addItem(mh.getMaMH());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        btnDangKy = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDKTinChi = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtSoTC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaLH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbThu = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTiet = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTenGV = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtTenLH = new javax.swing.JTextField();
        btnTaiLai = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        lbTenMon = new javax.swing.JLabel();
        cbxMaMH = new javax.swing.JComboBox<>();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("ĐĂNG KÍ TÍN CHỈ");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconsearch16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm Môn Học");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnDangKy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnDangKy.setText("Đăng Kí");
        btnDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangKyActionPerformed(evt);
            }
        });

        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconthoat16.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tblDKTinChi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Lớp", "Tên Lớp", "Tên Môn", "Tên PH", "Thứ", "Tiết", "Ngày Bắt Đầu", "Sĩ Số", "Tên GV"
            }
        ));
        tblDKTinChi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDKTinChiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDKTinChi);

        jLabel5.setText("Số tín chỉ:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Mã Lớp: ");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tên Lớp:");

        lbThu.setText("...");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Tiết Học: ");

        jLabel9.setText("Ngày Bắt Đầu: ");

        jLabel13.setText("Thứ: ");

        jLabel10.setText("Giảng viên:");

        btnTaiLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnTaiLai.setText("Tải Lại");
        btnTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaiLaiActionPerformed(evt);
            }
        });

        jLabel11.setText("Môn Học: ");

        lbTenMon.setText("Tên môn học");

        cbxMaMH.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxMaMHItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTimKiem)
                .addGap(50, 50, 50)
                .addComponent(btnDangKy)
                .addGap(93, 93, 93)
                .addComponent(btnTaiLai)
                .addGap(73, 73, 73)
                .addComponent(btnThoat)
                .addGap(104, 104, 104))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtTenLH, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtNgayBatDau, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                        .addComponent(txtTiet, javax.swing.GroupLayout.Alignment.LEADING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSoTC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbThu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenMon)
                    .addComponent(jLabel11)
                    .addComponent(cbxMaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTenLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(txtSoTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(lbThu))
                .addGap(20, 20, 20)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(btnDangKy)
                    .addComponent(btnThoat)
                    .addComponent(btnTaiLai))
                .addGap(14, 14, 14)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn thoát hay không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tblDKTinChiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDKTinChiMouseClicked
        selectedRow = tblDKTinChi.getSelectedRow();
        if (selectedRow >= 0) {
            GVDangKy gvdk = listgvdk.get(selectedRow);
            GiangVien gv = qlgvc.getGVByMaGV(gvdk.getMaGV());
            LopHoc lh;
            try {
                lh = qllhc.getLH(gvdk.getMaLH());
                MonHoc mh = qlmhc.getMH(lh.getMaMH());
                PhongHoc ph = qlphc.getPH(lh.getMaPH());
                txtMaLH.setText(gvdk.getMaLH());
                txtTenLH.setText(lh.getTenLH());
                txtTiet.setText(lh.getTiet());
                txtNgayBatDau.setText(lh.getNgayBatDau());
                cbxMaMH.setSelectedItem(lh.getMaMH());
                txtTenGV.setText(gv.getTenGV());
                txtSoTC.setText("" + mh.getSoTinChi());
                lbThu.setText(lh.getThu());
            } catch (ParseException ex) {
                Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_tblDKTinChiMouseClicked

    private void btnDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangKyActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng ký môn này không?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        SinhVien sv = qlsvc.getSVById(this.id);
        String maSV = sv.getMaSV();
        selectedRow = tblDKTinChi.getSelectedRow();
        if (selectedRow >= 0) {
            GVDangKy gvdk = listgvdk.get(selectedRow);
            String maLH = gvdk.getMaLH();
            qlsvdkc.dangKyLopHocSV(maSV, maLH);
        }
    }//GEN-LAST:event_btnDangKyActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        String maMH = cbxMaMH.getSelectedItem().toString();
        List<LopHoc> listLHSub = new ArrayList<>();
        try {
            listLHSub = qllhc.timKiemByMaMH(maMH);
        } catch (ParseException ex) {
            Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        List<GVDangKy> listGVDK = new ArrayList<>();

        for (LopHoc lh : listLHSub) {
            GVDangKy gvdk;
            try {
                gvdk = qlgvdkc.timKiemLopHocGVDaDangKy(lh.getMaLH());
                listGVDK.add(gvdk);
            } catch (ParseException ex) {
                Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }

        tblModel.setRowCount(0);
        int index = 1;
        for (GVDangKy gvdk : listGVDK) {
            GiangVien gv = qlgvc.getGVByMaGV(gvdk.getMaGV());
            LopHoc lh = new LopHoc();
            try {
                lh = qllhc.getLH(gvdk.getMaLH());
            } catch (ParseException ex) {
                Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            MonHoc mh = new MonHoc();
            try {
                mh = qlmhc.getMH(lh.getMaMH());
            } catch (ParseException ex) {
                Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            PhongHoc ph = qlphc.getPH(lh.getMaPH());
            tblModel.addRow(new Object[]{index++, lh.getMaLH(), lh.getTenLH(), mh.getTenMH(), lh.getThu(),
                lh.getTiet(), lh.getNgayBatDau(), lh.getSiSo(), gv.getTenGV(), ph.getTenPH()});
        }
        tblModel.fireTableDataChanged();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiLaiActionPerformed
        resetData();
        fillTable();
    }//GEN-LAST:event_btnTaiLaiActionPerformed

    private void cbxMaMHItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxMaMHItemStateChanged
        String maMH = cbxMaMH.getSelectedItem().toString();
        MonHoc mh = new MonHoc();
        try {
            mh = new QLMonHocController().getMH(maMH);
        } catch (ParseException ex) {
            Logger.getLogger(SVDangKyForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        lbTenMon.setText(mh.getTenMH());
    }//GEN-LAST:event_cbxMaMHItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVDangKyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SVDangKyForm("sv001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangKy;
    private javax.swing.JButton btnTaiLai;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JComboBox<String> cbxMaMH;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbTenMon;
    private javax.swing.JLabel lbThu;
    private javax.swing.JTable tblDKTinChi;
    private javax.swing.JTextField txtMaLH;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtSoTC;
    private javax.swing.JTextField txtTenGV;
    private javax.swing.JTextField txtTenLH;
    private javax.swing.JTextField txtTiet;
    // End of variables declaration//GEN-END:variables
}
