/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.SinhVien;

import controller.QLSinhVienController;
import java.awt.Color;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.SinhVien;

/**
 *
 * @author admin
 */
public class SVForm extends javax.swing.JFrame {

    private String id;
    private SinhVien sv;
    QLSinhVienController qlsvc = new QLSinhVienController();

    /**
     * Creates new form SVForm
     */
    public SVForm(String id) {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.id = id;
        viewInfor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        txtTenSV = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnCapNhap = new javax.swing.JButton();
        btnXemTKB = new javax.swing.JButton();
        dangXuat = new javax.swing.JButton();
        btnResetToDefault = new javax.swing.JButton();
        btnDKTinChi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông Tin Sinh Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N

        jLabel19.setText("Mã Sinh Viên:");

        jLabel20.setText("Tên Sinh Viên:");

        jLabel21.setText("Lớp:");

        jLabel22.setText("SĐT: ");

        jLabel23.setText("Địa Chỉ:");

        jLabel24.setText("Email: ");

        txtMaSV.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel24)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenSV)
                    .addComponent(txtLop)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(txtDiaChi)
                    .addComponent(txtMaSV)
                    .addComponent(txtEmail))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnCapNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/iconupdate16.png"))); // NOI18N
        btnCapNhap.setText("Cập Nhật");
        btnCapNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhapActionPerformed(evt);
            }
        });

        btnXemTKB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/xem16.png"))); // NOI18N
        btnXemTKB.setText("Xem TKB");
        btnXemTKB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXemTKBMouseClicked(evt);
            }
        });
        btnXemTKB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemTKBActionPerformed(evt);
            }
        });

        dangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icondx16.png"))); // NOI18N
        dangXuat.setText("Đăng Xuất");
        dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatActionPerformed(evt);
            }
        });

        btnResetToDefault.setText("Reset to Default");
        btnResetToDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetToDefaultActionPerformed(evt);
            }
        });

        btnDKTinChi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/dk16.png"))); // NOI18N
        btnDKTinChi.setText("Đăng Kí Tín Chỉ");
        btnDKTinChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDKTinChiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCapNhap)
                        .addGap(18, 18, 18)
                        .addComponent(btnResetToDefault)
                        .addGap(60, 60, 60)
                        .addComponent(dangXuat))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDKTinChi)
                            .addComponent(btnXemTKB, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(btnDKTinChi)
                        .addGap(18, 18, 18)
                        .addComponent(btnXemTKB)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResetToDefault)
                    .addComponent(btnCapNhap)
                    .addComponent(dangXuat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewInfor() {
        sv = qlsvc.getSVById(id);
        txtMaSV.setText(sv.getMaSV());
        txtTenSV.setText(sv.getTenSV());
        txtLop.setText(sv.getLop());
        txtSoDT.setText(sv.getSoDT());
        txtDiaChi.setText(sv.getDiaChi());
        txtEmail.setText(sv.getEmail());
    }

    private void resetData() {
        String empty = "";
        txtMaSV.setText(empty);
        txtTenSV.setText(empty);
        txtLop.setText(empty);
        txtSoDT.setText(empty);
        txtDiaChi.setText(empty);
        txtEmail.setText(empty);
        txtMaSV.setBackground(null);
        txtTenSV.setBackground(null);
        txtLop.setBackground(null);
        txtSoDT.setBackground(null);
        txtDiaChi.setBackground(null);
        txtEmail.setBackground(null);
    }

    private boolean isHadEmptyField() {
        StringBuffer sb = new StringBuffer();
        if (txtMaSV.getText().isBlank()) {
            sb.append("Mã sinh viên không đc để trống\n");
            txtMaSV.setBackground(Color.CYAN);
        } else {
            txtMaSV.setBackground(null);
        }
        if (txtTenSV.getText().isBlank()) {
            sb.append("Tên sinh viên không đc để trống\n");
            txtTenSV.setBackground(Color.CYAN);
        } else {
            txtTenSV.setBackground(null);
        }
        if (txtLop.getText().isBlank()) {
            sb.append("Lớp không đc để trống\n");
            txtLop.setBackground(Color.CYAN);
        } else if (txtLop.getText().trim().length() > 12) {
            sb.append("Lớp không tồn tại\n");
            txtLop.setBackground(Color.CYAN);
        } else {
            txtLop.setBackground(null);
        }
        if (txtSoDT.getText().isBlank() || txtSoDT.getText().trim().length() != 10) {
            sb.append("Số điện thoại không đc để trống và phải điền đủ 10 số\n");
            txtSoDT.setBackground(Color.CYAN);
        } else {
            txtSoDT.setBackground(null);
        }
        if (txtDiaChi.getText().isBlank()) {
            sb.append("Địa chỉ không đc để trống\n");
            txtDiaChi.setBackground(Color.CYAN);
        } else {
            txtDiaChi.setBackground(null);
        }
        if (txtEmail.getText().isBlank()) {
            sb.append("Email không đc để trống\n");
            txtEmail.setBackground(Color.CYAN);
        } else {
            txtEmail.setBackground(null);
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Error", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
    }

    private void btnXemTKBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXemTKBMouseClicked
        //        TKBView TKB = new TKBView();
        //        TKB.show();
    }//GEN-LAST:event_btnXemTKBMouseClicked

    private void btnCapNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhapActionPerformed
        if (!isHadEmptyField()) {
            int choice = JOptionPane.showConfirmDialog(this,
                    "Bạn có chắc muốn cập nhập thông tin hay không?",
                    "Hỏi", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.NO_OPTION) {
                return;
            }
            String maSV = txtMaSV.getText().trim();
            String tenSV = txtTenSV.getText().trim();
            String lop = txtLop.getText().trim();
            String soDT = txtSoDT.getText().trim();
            String diaChi = txtDiaChi.getText().trim();
            String email = txtEmail.getText().trim();
            sv = new SinhVien(maSV, tenSV, lop, soDT, diaChi, email, this.id);
            qlsvc.suaSV(sv);
        }
    }//GEN-LAST:event_btnCapNhapActionPerformed

    private void btnResetToDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetToDefaultActionPerformed
        // Trả lại dữ liệu ban đầu
        resetData();
        viewInfor();
    }//GEN-LAST:event_btnResetToDefaultActionPerformed

    private void dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc muốn đăng xuất?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        dispose();
    }//GEN-LAST:event_dangXuatActionPerformed

    private void btnDKTinChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDKTinChiActionPerformed
        try {
            new SVDangKyForm(id);
        } catch (ParseException ex) {
            Logger.getLogger(SVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDKTinChiActionPerformed

    private void btnXemTKBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemTKBActionPerformed
        try {
            new TKBForm(id);
        } catch (ParseException ex) {
            Logger.getLogger(SVForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnXemTKBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SVForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new SVForm("sv001").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhap;
    private javax.swing.JButton btnDKTinChi;
    private javax.swing.JButton btnResetToDefault;
    private javax.swing.JButton btnXemTKB;
    private javax.swing.JButton dangXuat;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenSV;
    // End of variables declaration//GEN-END:variables
}
